### ISSUE TITLE
nbconvert missing template subdirectory

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/manipulation#106]
Running bazel on a clean ubuntu install with my (upcoming) hermitic-only pip caused one failure:

```
ERROR: /home/russt/manipulation/figures/BUILD.bazel:10:14: Executing genrule //figures:grasp_frames_nbconvert failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/russt/.cache/bazel/_bazel_russt/7bcbcd19e064ca0197e4cfaf8f9df35e/sandbox/linux-sandbox/1279/execroot/manipulation/bazel-out/k8-fastbuild/bin/htmlbook/tools/jupyter/nbconvert.runfiles/pip/pypi__traitlets/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/russt/.cache/bazel/_bazel_russt/7bcbcd19e064ca0197e4cfaf8f9df35e/sandbox/linux-sandbox/1279/execroot/manipulation/bazel-out/k8-fastbuild/bin/htmlbook/tools/jupyter/nbconvert.runfiles/manipulation/htmlbook/tools/jupyter/nbconvert_script.py", line 31, in <module>
    main(sys.argv[1])
  File "/home/russt/.cache/bazel/_bazel_russt/7bcbcd19e064ca0197e4cfaf8f9df35e/sandbox/linux-sandbox/1279/execroot/manipulation/bazel-out/k8-fastbuild/bin/htmlbook/tools/jupyter/nbconvert.runfiles/manipulation/htmlbook/tools/jupyter/nbconvert_script.py", line 19, in main
    exporter = PythonExporter()
  File "/home/russt/.cache/bazel/_bazel_russt/7bcbcd19e064ca0197e4cfaf8f9df35e/sandbox/linux-sandbox/1279/execroot/manipulation/bazel-out/k8-fastbuild/bin/htmlbook/tools/jupyter/nbconvert.runfiles/pip/pypi__nbconvert/nbconvert/exporters/templateexporter.py", line 325, in __init__
    super().__init__(config=config, **kw)
  File "/home/russt/.cache/bazel/_bazel_russt/7bcbcd19e064ca0197e4cfaf8f9df35e/sandbox/linux-sandbox/1279/execroot/manipulation/bazel-out/k8-fastbuild/bin/htmlbook/tools/jupyter/nbconvert.runfiles/pip/pypi__nbconvert/nbconvert/exporters/exporter.py", line 114, in __init__
    self._init_preprocessors()
  File "/home/russt/.cache/bazel/_bazel_russt/7bcbcd19e064ca0197e4cfaf8f9df35e/sandbox/linux-sandbox/1279/execroot/manipulation/bazel-out/k8-fastbuild/bin/htmlbook/tools/jupyter/nbconvert.runfiles/pip/pypi__nbconvert/nbconvert/exporters/templateexporter.py", line 491, in _init_preprocessors
    conf = self._get_conf()
  File "/home/russt/.cache/bazel/_bazel_russt/7bcbcd19e064ca0197e4cfaf8f9df35e/sandbox/linux-sandbox/1279/execroot/manipulation/bazel-out/k8-fastbuild/bin/htmlbook/tools/jupyter/nbconvert.runfiles/pip/pypi__nbconvert/nbconvert/exporters/templateexporter.py", line 507, in _get_conf
    for path in map(Path, self.template_paths):
  File "/home/russt/.cache/bazel/_bazel_russt/7bcbcd19e064ca0197e4cfaf8f9df35e/sandbox/linux-sandbox/1279/execroot/manipulation/bazel-out/k8-fastbuild/bin/htmlbook/tools/jupyter/nbconvert.runfiles/pip/pypi__traitlets/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/home/russt/.cache/bazel/_bazel_russt/7bcbcd19e064ca0197e4cfaf8f9df35e/sandbox/linux-sandbox/1279/execroot/manipulation/bazel-out/k8-fastbuild/bin/htmlbook/tools/jupyter/nbconvert.runfiles/pip/pypi__traitlets/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/home/russt/.cache/bazel/_bazel_russt/7bcbcd19e064ca0197e4cfaf8f9df35e/sandbox/linux-sandbox/1279/execroot/manipulation/bazel-out/k8-fastbuild/bin/htmlbook/tools/jupyter/nbconvert.runfiles/pip/pypi__nbconvert/nbconvert/exporters/templateexporter.py", line 518, in _template_paths
    template_names = self.get_template_names()
  File "/home/russt/.cache/bazel/_bazel_russt/7bcbcd19e064ca0197e4cfaf8f9df35e/sandbox/linux-sandbox/1279/execroot/manipulation/bazel-out/k8-fastbuild/bin/htmlbook/tools/jupyter/nbconvert.runfiles/pip/pypi__nbconvert/nbconvert/exporters/templateexporter.py", line 601, in get_template_names
    raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (base_template, paths))
ValueError: No template sub-directory with name 'python' found in the following paths:
	/home/russt/.local/share/jupyter
	/usr/local/share/jupyter
	/usr/share/jupyter
```

For now, I've just pegged the nbconvert revision on ubuntu.

**Comment by RussTedrake** [comment]
This is the same issue as https://github.com/RobotLocomotion/drake/issues/14250
